### ISSUE TITLE
example launch files reference incorrect subdirectory

### ISSUE THREAD

**Issue by githubfrond** [boschresearch/fmi_adapter#2]
Great fmi_adapter, thanks so much!

Had to edit launch files to reference the **/share** subdirectory in order to execute their correct .fmu
for example,
<param name="fmu_path" value="$(find fmi_adapter_examples)/**share**/DampedPendulum.fmu" />

**Comment by ralph-lange** [comment]
Thank you for reporting this issue, @githubfrond. If you use a separate install space (i.e. `catkin config --install`), the example launch files work without any changes. Nevertheless, I'll fix it.

**Comment by ralph-lange** [comment]
Fixed by https://github.com/boschresearch/fmi_adapter/commit/5dc66e4e242a840beedffd978b476e842b930b87
