### ISSUE TITLE
Simulating multiple FMU's in the loop

### ISSUE THREAD

**Issue by sandeepparameshwara** [boschresearch/fmi_adapter#4]
Hello Mr. Lange,

Thanks for this wonderful package. I am currently facing an issue. I am running 2 FMU(from Dymola) nodes in the loop and they are subscribed to each other's topics. Since the package creates separate topics for vectorized signals, I have many publishers and subscribers. I am running the simulation at the rate of 500 Hz. The simulation is not running as expected and I highly doubt that it's due to unsuccessful communication between the nodes. Since the float64 values don't have timestamps, I don't have any ways to sync the data while publishing. I guess, due to this asynchronous communication, this is leading to failure. I tested the FMU's in python (with Fmpy package) and they work perfectly well. Is there any way to address this issue? I have 4 inputs and I need to publish them at the same time and similarly read subscribed topics at the same time. I initially thought that this won't be a problem, but now I can think of only this reason. Any inputs from you will be helpful.

Thank you
Sandeep

**Comment by ralph-lange** [comment]
Hi Sandeep, did you have a look at the [library mode](https://github.com/boschresearch/fmi_adapter/tree/master/fmi_adapter#fmi_adapter-library)? It allows to map the inputs and outputs of an FMU to complex message types and gives more control on the execution. There is no complete example on such usage, but there are some [code snippets](https://github.com/boschresearch/fmi_adapter/tree/master/fmi_adapter#running-an-fmu-inside-a-ros-node-or-library) in the documentation.
If you have access to Springer Link, there is a longer example in Section 3.3.3 of this [book chapter](https://github.com/boschresearch/fmi_adapter/tree/master/fmi_adapter#running-an-fmu-inside-a-ros-node-or-library).
Please don't hesitate to ask further questions!
Best regards, Ralph

**Comment by sandeepparameshwara** [comment]
Thank you for the inputs, will look at them. Will reopen he issue only if necessary.

Best regards
Sandeep
