### ISSUE TITLE
Given FMU file '' not found or cannot be read!

### ISSUE THREAD

**Issue by bilalCatic** [boschresearch/fmi_adapter#6]
Hello again

I have trouble changing state of the `fmi_adapter` node from `unconfigured` to the `configured` (and later `active`).

yaml file with params : 

>fmi_adapter_node:
>¨¨¨¨¨¨ros__parameters:
>¨¨¨¨¨¨¨¨¨¨fmu_path: "/tmp/OpenModelica_ros123/OMEdit/DampedPendulum/DampedPendulum.fmu"

Steps I tried : 

1. `ros2 run fmi_adapter fmi_adapter_node __params:=my_params.yaml` (my_params.yaml file is in the directory where I executed command, it is populated as explained in the paper cited in the README file and shown above [I tried with different quotes and without quotes])
2. Second terminal : `ros2 lifecycle set /fmi_adapter_node configure` 

After step 2, in the second terminal I got the error `Transitioning failed` and in the first terminal I got errors : 

[ERROR]... `Caught exception in callback for transition 10`
[ERROR]... `Original error: Given FMU file '' not found or cannot be read!`
[WARN].... `Error occurred while doing error handling.`

Based on the error, it seems like I didn't set correctly path to the FMU file but I don't know what is wrong

Alternatively, running through launch works : 

`ros2 launch fmi_adapter fmi_adapter_node.launch.py fmu_path:=/tmp/OpenModelica_ros123/OMEdit/DampedPendulum/DampedPendulum.fmu`

This way, I can see output with `ros2 topic echo /revolute1_angle`

**Comment by ralph-lange** [comment]
The command line interface for `ros2` has been changed after Dashing. You have to pass the parameter file as follows now:

```
ros2 run fmi_adapter fmi_adapter_node --ros-args --params-file my_params.yml
```

See https://docs.ros.org/en/foxy/Tutorials/Parameters/Understanding-ROS2-Parameters.html#load-parameter-file for details.
